[project]
name = "expense-tracker-remote-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ritik", email = "dcba4259@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastmcp>=4.0.5",
]

[project.scripts]
expense-tracker-remote-mcp = "expense_tracker_remote_mcp:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
